[plugin]
id = "com.jacobtread.tilepad.obs-studio"
name = "OBS Studio"
version = "0.0.1"
authors = ["Jacobtread"]
description = "Tilepad OBS actions"

[category]
label = "OBS"
icon = "images/obs.png"

[[bin.native]]
os = "windows"
arch = "x64"
path = "bin/plugin-windows-x64.exe"

[[bin.native]]
os = "windows"
arch = "x86"
path = "bin/plugin-windows-x86.exe"

[[bin.native]]
os = "linux"
arch = "x64"
path = "bin/plugin-linux-x64"

[[bin.native]]
os = "linux"
arch = "x86"
path = "bin/plugin-linux-x86"

[actions.recording]
label = "Recording"
description = "Interaction with OBS recording capabilities"
inspector = "ui/connect.html"

[actions.streaming]
label = "Stream"
description = "Interaction with OBS streaming capabilities"
inspector = "ui/connect.html"

[actions.virtual_camera]
label = "Virtual Cam"
description = "Interaction with OBS virtual camera capabilities"
inspector = "ui/connect.html"

[actions.switch_scene]
label = "Switch Scene"
description = "Switch to a specific scene"
inspector = "ui/connect.html"

[actions.switch_profile]
label = "Switch Profile"
description = "Switch to a specific OBS profile"
inspector = "ui/connect.html"
